starter-enabled: false

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
#  cache:
#    type: redis
#    cache-names: moviesCache
#    time-to-live: 10s
#  data:
#    redis:
#      host: localhost
#      port: 6379

#  datasource:
#    url: jdbc:postgresql://postgres:5432/postgres-db
#    username: postgres
#    password: postgres
#  data:
#    redis:
#      host: redis
#      port: 6379

#logging:
#  level:
#    org.springframework.data.redis: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics #, caches
  metrics:
    export:
      prometheus:
        enabled: true